---
- name: This sets up an httpd webserver
  hosts: application-server
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Install apache packages
    apt:
      name: apache2
      state: present
  - name: Copy php application on application server
    synchronize:
      src: ./chat_application
      dest: /var/www/html
  - name: Copy php-start.sh on Application server
    synchronize:
      src: ./php-start.sh
      dest: /var/www/
  - name: ensure apache is running
    service:
      name: apache2
      state: started
  - name: Install Composer
    composer:
        command: install
        working_dir: /var/www/html/chat_application
  - name: Start php application
    script: /var/www/html/php-start.sh
