---
- name: This sets up an httpd webserver
  hosts: application-server
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: present
  - name: Copy php application on application server
    copy:
      src: ./chat_application
      dest: /var/www/html/
      force: no 
  - name: ensure apache2 is running
    service:
      name: httpd
      state: started
